### ISSUE TITLE
project AnimationExamples missing in chapter 9

### ISSUE THREAD

**Issue by vic-ht** [IanGClifton/auid2#1]
Hi ! :)  In the book, page 240 in Kindle, at the end of "Time Interpolators", sais there's an "AnimationExamples" project in the chapter09 folder, but can't find it.

**Comment by IanGClifton** [comment]
You're right; looks like it's missing. I'll track it down and try to get it uploaded shortly

**Comment by IanGClifton** [comment]
I added the "AnimationExamples" project to chapter 9. Sorry I didn't catch that before!

**Comment by vic-ht** [comment]
Thank you Ian !!
